name: farm_market_app
description: Farm market application.
version: 1.0.0+1
publish_to: "none"

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  auto_route: ^4.0.1
  badges: ^2.0.3
  bloc_concurrency: ^0.2.0
  cached_network_image: ^3.2.1
  cloud_firestore: ^3.1.17
  cupertino_icons: ^1.0.2
  firebase_core: ^1.17.1
  firebase_remote_config: ^2.0.8
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  flutter_map: ^1.0.0
  flutter_secure_storage: ^5.0.2
  freezed_annotation: ^2.0.3
  json_annotation: ^4.5.0
  pull_to_refresh: ^2.0.0
  shared_preferences: ^2.0.15
  uuid: ^3.0.6

dev_dependencies:
  auto_route_generator: ^4.0.0
  build_runner: ^2.1.11
  flutter_lints: ^2.0.0
  freezed: ^2.0.3+1
  intl_utils: ^2.6.1
  json_serializable: ^6.2.0

flutter_intl:
  enabled: true
  main_locale: ru_RU
  arb_dir: lib/utils/l10n/arb
  output_dir: lib/utils/l10n/generated

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/img/
    - assets/fonts/

  fonts:
    - family: Manrope
      fonts:
        - asset: assets/fonts/Manrope-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Manrope-Bold.ttf
          weight: 700
        - asset: assets/fonts/Manrope-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Manrope-Medium.ttf
          weight: 500
        - asset: assets/fonts/Manrope-Regular.ttf
          weight: 400
        - asset: assets/fonts/Manrope-Light.ttf
          weight: 300
        - asset: assets/fonts/Manrope-ExtraLight.ttf
          weight: 200
